//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mboxview.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_MAIN_TOOLBAR                101
#define IDD_CPICTURECTRLDEMO_DIALOG     102
#define IDS_DAY_MONTH_YEAR              102
#define IDS_MONTH_DAY_YEAR              103
#define IDS_YEAR_MONTH_DAY              104
#define IDS_PAGE_CODE_LIST_CODEPAGE_ID  105
#define IDS_PAGE_CODE_LIST_CODEPAGE_NAME 106
#define IDS_PAGE_CODE_LIST_MAX_CHAR_SIZE 107
#define IDS_STRING_FROM                 108
#define IDS_STRING_TO                   109
#define IDS_STRING_SUBJECT              110
#define IDS_STRING_SIZE                 111
#define IDS_STRING_DATE_LOCAL           112
#define IDS_STRING_DATE_GMT             113
#define IDD_MyCDialogBar                115
#define IDR_MAINFRAME                   128
#define IDR_mboxviewTYPE                129
#define IDS_SELECT_FOLDER               129
#define IDR_POPUP_TOOLBAR               131
#define IDD_CONTROLS_DLG                154
#define IDB_IL_TREE                     155
#define IDD_FIND                        156
#define IDD_OPTIONS                     158
#define IDD_EXPORT_TO_CSV               166
#define IDD_OPEN_FOLDER                 168
#define IDB_PRINT                       171
#define IDB_FOLDER                      176
#define IDD_FIND_ADVANCED               177
#define IDD_FIND_IN_MAIL                180
#define IDD_EDITOR                      194
#define IDD_PRINT_DLG                   195
#define IDD_INPUT_BOX_DLG               201
#define IDS_DESC_TITLE                  202
#define IDS_TITLE_SUBJECT               202
#define IDS_DESC_TITLE1                 203
#define IDS_TITLE_FROM                  203
#define IDD_ATTACHMENTS_CONFIG          203
#define IDS_DESC_NONE                   204
#define IDS_DESC_TITLE3                 205
#define IDS_TITLE_TO                    205
#define IDD_CHECK_LIST_BOX_DLG          205
#define IDS_DESC_TITLE2                 206
#define IDS_TITLE_DATE                  206
#define IDS_DESC_BODY                   207
#define IDS_TITLE_BODY                  207
#define IDB_PAPER_CLIP                  207
#define IDD_NAME_TEMPL_DLG              208
#define IDS_TITLE_CC                    208
#define IDS_TITLE_BCC                   209
#define IDS_TITLE_MAIL_HEADER           210
#define IDD_COLOR_STYLE_DLG             216
#define IDD_HTML_PDF_HDR_DLG            218
#define IDD_GENERIC_FONT_DLG            220
#define IDB_BITMAP1                     222
#define IDD_FIND_FILTER_DLG             223
#define IDD_DIALOG1                     225
#define IDD_OPEN_ARCHIVE_DLG            225
#define IDD_SMTP_DLG                    226
#define IDD_FORWARD_EMAIL               228
#define IDD_DATA_FOLDER_DLG             230
#define IDD_MERGE_FOLDER_AND_SUBFOLDERS 232
#define IDD_DEV_CREATE_ARCHIVE          234
#define IDD_PAGE_CODE_LIST_DLG          236
#define IDD_PROGRESS_DLG                238
#define IDD_GENERAL_OPTIONS_DLG         240
#define IDD_LANG_LIST_DLG               242
#define IDD_DIALOG_FONT_SIZE            244
#define IDC_BUTTON_PREV                 1001
#define IDC_PRT_PAGE_SETP               1001
#define IDC_EDIT_RESET                  1001
#define IDC_SRCFTIME                    1001
#define IDC_BUTTON2                     1002
#define IDC_BUTTON_NEXT                 1002
#define IDC_BUTTON_ROTATE               1003
#define IDC_STATIC_PICTURE              1006
#define IDC_COMPANY_URL                 1041
#define IDC_TREE                        1042
#define IDC_LIST                        1043
#define IDC_BROWSER                     1044
#define IDC_EXPLORER                    1045
#define IDC_ATTACHMENTS                 1046
#define IDC_STRING                      1047
#define IDC_CASE                        1048
#define IDC_WHOLE                       1049
#define IDC_STATIC1                     1050
#define IDC_DMY                         1051
#define IDC_MDY                         1052
#define IDC_YMD                         1053
#define IDC_DATETIMEPICKER1             1053
#define IDC_DATETIMEPICKER2             1054
#define IDC_SCOPE                       1056
#define IDC_EXPORT_EML                  1056
#define IDC_SEARCH_PREV                 1056
#define IDC_ENCODING_NONE               1056
#define IDC_ARCHIVE_LIST                1056
#define IDC_FILTER1                     1056
#define IDC_PRT_DO_NOT_PROMPT           1056
#define IDC_FONT_DFLT                   1056
#define IDC_FILTER_NUMBER0              1056
#define IDC_RADIO2                      1057
#define IDC_EXPORT_EML_Y                1057
#define IDC_FIND_LIST                   1057
#define IDC_FILTER_NUMBER1              1057
#define IDC_MERGE_ROOT_FOLDER_AND_SUBFOLDERS 1057
#define IDC_OPEN_LINK_IN_NEW_TAB        1057
#define IDC_RADIO_FONT_CUSTOM           1057
#define IDC_FILTER_NUMBER3              1058
#define IDC_CHECK1                      1059
#define IDC_FILTERDATES                 1059
#define IDC_EXPORT_FROM                 1059
#define IDC_CHECK_FROM_A                1059
#define IDC_FILE_DATE                   1059
#define IDC_ENHANCED_SELECT_FOLDER      1059
#define IDC_ALL_ATTACHMENT_TYPES        1059
#define IDC_COLOR_CHECK                 1059
#define IDC_FLD_NAME_BOLD               1059
#define IDC_FILTER_NUMBER2              1059
#define IDC_SSL_ON                      1059
#define IDC_RELAX_MBOX_FILE_VALIDATION  1059
#define IDC_STATIC_FORWARD_CC           1059
#define IDC_CHECK_TO_A                  1060
#define IDC_EDIT_TO_CHECKED             1060
#define IDC_ALL_ATTACHMENT_TYPES_INDICATOR 1060
#define IDC_FILTER_NUMBER4              1060
#define IDC_CHECK_SUBJECT_A             1061
#define IDC_EDIT_SUBJECT_CHECKED        1061
#define IDC_CHECK_MESSAGE_A             1062
#define IDC_EDIT_MESSAGE_CHECKED        1062
#define IDC_DONATION                    1063
#define IDC_CHECK_ATTACHMENTS_A         1063
#define IDC_EDIT_ATTACHMENT_CHECKED     1063
#define IDC_FILTERDATES_A               1064
#define IDC_EDIT_ATTACHMENT_NAME_CHECKED 1064
#define IDC_PROGRESS_BAR_DELAY          1065
#define IDC_MSEDGE                      1066
#define IDC_SUBJ_ID                     1070
#define IDC_FROM_ID                     1071
#define IDC_CONFIG_FOLDER_STYLE_1       1071
#define IDC_TO_ID                       1072
#define IDC_CONFIG_FOLDER_STYLE_2       1072
#define IDC_CONFIG_FOLDER_STYLE_3       1073
#define IDC_SHOW_CHARSETS               1074
#define IDC_SHOW_CHARSETS_Y             1075
#define IDC_CHECK_FROM                  1076
#define IDC_CHECK_TO                    1077
#define IDC_CHECK_SUBJECT               1078
#define IDC_CHECK_CONTENT               1079
#define IDC_CHECK6                      1080
#define IDC_CHECK_ATTACHMENT            1080
#define IDC_EDIT_CC_CASE                1080
#define IDC_SEPARATE_TEXT               1080
#define IDC_SEARCH_NEXT                 1081
#define IDC_BUTTON_ZOOM                 1083
#define IDC_IMAGE_VIEWER                1085
#define IDC_EXPORT_SUBJECT              1085
#define IDC_MATCH_CASE                  1085
#define IDC_EDIT_FROM_CASE              1085
#define IDC_FILE_FROM                   1085
#define IDC_CHECK_BCC                   1085
#define IDC_TEMPL_FROM_DOMAIN_NAME      1085
#define IDC_TIME_TYPE                   1086
#define IDC_MATCH_CASE2                 1086
#define IDC_EDIT_TO_CASE                1086
#define IDC_ATTACHMENT_TYPE_INDICATOR   1086
#define IDC_TEMPL_TO_DOMAIN_NAME        1086
#define IDC_TIME_LOCAL                  1087
#define IDC_MATCH_CASE3                 1087
#define IDC_EDIT_SUBJECT_CASE           1087
#define IDC_TIME_GMT                    1088
#define IDC_MATCH_CASE4                 1088
#define IDC_EDIT_MESSAGE_CASE           1088
#define IDC_GROUP_PROGRES_BAR           1089
#define IDC_MATCH_CASE5                 1089
#define IDC_EDIT_ATTACHMENT_CASE        1089
#define IDC_GROUP_EML                   1090
#define IDC_EDIT_ATTACHMENT_NAME_CASE   1090
#define IDC_GROUP_SET_IDS               1091
#define IDC_OPTIONS_SET_IDS             1091
#define IDC_GROUP_SHOW_CHARSETS         1092
#define IDC_GROUP_FROM_TO_SUBJ          1093
#define IDC_OPTIONS_SEPARATOR           1094
#define IDC_PICTURE_VIEWER              1095
#define IDC_EXPORT_TO                   1096
#define IDC_EXPORT_DATE                 1097
#define IDC_EXPORT_MESSAGE              1098
#define IDC_ENCODING_UTF8               1106
#define IDC_ENCODING_CODE_PAGE          1107
#define IDC_ENCODING_CODE_PAGE_ID       1108
#define IDC_BUTTON_PRT                  1109
#define IDC_EDIT1                       1110
#define IDC_EDIT_FROM                   1110
#define IDC_FILE_NAME_FORMAT            1110
#define IDC_FILE_NAME_ADJUSTED_MAX_SIZE 1110
#define IDC_EXPORT_MESSAGE_LIMIT_CHARS  1110
#define IDC_MATCH_WORD                  1111
#define IDC_EDIT_FROM_WHOLE             1111
#define IDC_REGULAR_EXPR                1112
#define IDC_EDIT2                       1113
#define IDC_EDIT_TO                     1113
#define IDC_FILE_NAME_MAX_SIZE          1113
#define IDC_MATCH_WORD2                 1114
#define IDC_EDIT_TO_WHOLE               1114
#define IDC_REGULAR_EXPR2               1115
#define IDC_EDIT3                       1116
#define IDC_EDIT_SUBJECT                1116
#define IDC_CHROME_EXE_PATH             1116
#define IDC_USER_ACCOUNT                1116
#define IDC_EDIT_FORWARD_BCC            1116
#define IDC_MAIL_LEADING_CNT            1116
#define IDC_MATCH_WORD3                 1117
#define IDC_EDIT_SUBJECT_WHOLE          1117
#define IDC_REGULAR_EXPR3               1118
#define IDC_EDIT4                       1119
#define IDC_EDIT_MESSAGE                1119
#define IDC_HTML2PDF_SCRIPT_PATH        1119
#define IDC_USER_PASSWORD               1119
#define IDC_EDIT_FORWARD_TEXT           1119
#define IDC_MAIL_TRAILING_CNT           1119
#define IDC_MATCH_WORD4                 1120
#define IDC_EDIT_MESSAGE_WHOLE          1120
#define IDC_REGULAR_EXPR4               1121
#define IDC_EDIT5                       1122
#define IDC_EDIT_ATTACHMENT             1122
#define IDC_EDIT_FORWARD_SERVICE        1122
#define IDC_CREATED_ARCHIVE             1122
#define IDC_MATCH_WORD5                 1123
#define IDC_EDIT_ATTACHMENT_WHOLE       1123
#define IDC_REGULAR_EXPR5               1124
#define IDC_EDIT_ATTACHMENT_NAME        1124
#define IDC_SEARCH_BACKWARDS_A          1125
#define IDC_EDIT_ATTACHMENT_NAME_WHOLE  1125
#define IDC_MATCH_WORDS_ALL_A           1142
#define IDC_EDIT_SET_ALL_WHOLE          1142
#define IDC_MATCH_CASE_ALL_A            1143
#define IDC_EDIT_SET_ALL_CASE           1143
#define IDC_REGEX_ALL_A                 1144
#define IDC_CHECK_HIGHLIGHT_ALL         1145
#define IDC_SLIDER_ZOOM                 1146
#define IDC_SLIDER_POS                  1149
#define IDC_EXPORT_MESSAGE_LIMIT        1150
#define IDC_FIND_ALL_OCCURENCES         1151
#define IDC_CHECK_FIND_ALL              1151
#define IDC_EDIT_LIST                   1152
#define IDC_EDIT_FROM_CHECKED           1157
#define IDC_FILE_TIME                   1158
#define IDC_FILE_TO                     1159
#define IDC_FILE_SUBJECT                1160
#define IDC_FILE_UNIQUE_ID              1161
#define IDC_PRT_PREVIEW_DIALOG          1162
#define IDC_PRT_PRINT_DIALOG            1163
#define IDC_HTML2PDF_SCRIPT_TYPE        1164
#define IDC_USER_SCRIPT                 1165
#define IDC_EDIT_CC_CHECKED             1169
#define IDC_EDIT_CC                     1170
#define IDC_EDIT_CC_WHOLE               1171
#define IDC_EDIT_BCC_CHECKED            1172
#define IDC_EDIT_BCC                    1173
#define IDC_EDIT_BCC_WHOLE              1174
#define IDC_EDIT_BCC_CASE               1175
#define IDC_PRINT_TO_SEPARATE_FILES     1176
#define IDC_SEPARATE_PDF                1177
#define IDC_SEPARATE_HTML               1178
#define IDC_STATIC_PDF_OPTIONS          1179
#define IDC_ADD_HDR_COLOR               1180
#define IDC_PAGE_BREAK                  1181
#define IDC_EXPORT_CC                   1182
#define IDC_EXPORT_BCC                  1183
#define IDC_CHECK2                      1184
#define IDC_CHECK_CC                    1184
#define IDC_EXPORT_ATTACHMENT_NAMES     1184
#define IDC_CHECK_NEGATE_FIND_CRITERIA  1184
#define IDC_KEEP_BODY_BKGRND_COLOR      1184
#define IDC_TEMPL_FROM_USERNAME         1184
#define IDC_APPEND_SINGLE_MAIL_VIEW     1184
#define IDC_RELATIVE_ATTACHMENT_FILE_PATH 1184
#define IDC_TEMPL_TO_USERNAME           1185
#define IDC_INPUT_LABEL                 1186
#define IDC_LIST2                       1187
#define IDC_CODE_PAGE_ENUMERATION       1187
#define IDC_CHECK_ATTACHMENT_NAME       1188
#define IDC_CHECK_NEGATE_SEARCH_CRITERIA 1189
#define IDC_LICENSE                     1190
#define IDC_FOLDER_LIST                 1191
#define IDC_ATTACHMENT_WNDW_CFG         1192
#define IDC_ATTACHMENT_MAX_SIZE         1193
#define IDC_LIST1                       1194
#define IDC_CUSTOM_TEMPLATE             1195
#define IDC_SET_CUSTOM_TEMPLATE         1196
#define IDC_LABEL_LIST                  1197
#define IDC_EDIT_TEMPL_FMT              1199
#define IDC_EDIT_DATE_FMT               1200
#define IDC_TEMPL_FROM_ADDRESS_TEXT     1206
#define IDC_TEMPL_WHITE_TO_UNDERSCORE   1207
#define IDC_TEMPL_TO_ADDRESS_TEXT       1208
#define IDC_COLOR_BUTTON                1212
#define IDC_BUTTON_HELP                 1221
#define IDC_BUTTON_CLOSE                1222
#define IDC_PICK_FAMILY_FONT            1223
#define IDC_FONT_CUSTOM                 1224
#define IDC_FLD_SIZE                    1225
#define IDC_PICK_CONCRETE_FONT          1226
#define IDC_HDR_FLD_HELP                1227
#define IDC_HDR_FLD_NAME                1228
#define IDC_HDR_FLD_TEXT                1229
#define IDC_BUTTON1                     1230
#define IDC_HTML_PDF_CNF                1230
#define IDC_EXPORT_ATTACHMENT_SEPARATOR 1231
#define IDC_EDIT_MAIL_HDR               1232
#define IDC_RULE_NUMBER_TEXT            1237
#define IDC_RULE_TEXT                   1238
#define IDC_SINGLE_TO                   1239
#define IDC_FILTER_NUMBER5              1240
#define IDC_EDIT_TARGET_FOLDER          1241
#define IDC_EDIT_ARCHIVE_FILE_NAME      1242
#define IDC_EDIT_DFLT_FOLDER            1243
#define IDC_CHECK4                      1244
#define IDC_HEADER_AND_FOOTER           1244
#define IDC_PLAIN_TEXT                  1244
#define IDC_APPEND_SINGLE_MAIL_PRINT    1244
#define IDC_GMAIL                       1245
#define IDC_YAHOO                       1246
#define IDC_OUTLOOK                     1247
#define IDC_CUSTOM                      1248
#define IDC_SMTP_SERVER_ADDR            1249
#define IDC_SMTP_SERVER_PORT            1250
#define IDC_TLS_OPTION                  1251
#define IDC_SSL_OPTION                  1252
#define IDC_STATIC_FORWARD_BCC          1252
#define IDC_RADIO3                      1253
#define IDC_BBUTTON_SAVE                1254
#define IDC_SMTP_SERVER_HELP            1256
#define IDC_FORWARD_TO                  1257
#define IDC_STATIC_FORWARD_TO           1257
#define IDC_EDIT_FORWARD_TO             1258
#define IDC_EDIT_FORWARD_CC             1259
#define IDC_FORWARD_USER_TEXT           1261
#define IDC_STATIC_FORWARD_USER_TEXT    1261
#define IDC_EDIT_FORWARD_SUBJECT        1262
#define IDC_FORWARD_CLEAR               1263
#define IDC_EDIT_FORWARD_FROM           1264
#define IDC_FORWARD_MAX_MAIL_SIZE       1265
#define IDC_FORWARD_MAX_MAIL_SIZE_LABEL 1265
#define IDC_MAX_MAIL_SIZE               1266
#define IDC_SELECT_DATA_FOLDER_BUTTON   1268
#define IDC_EDIT_WIN_APP_DATA_FOLDER    1269
#define IDC_USER_SELECTED_FOLDER_PATH   1270
#define IDC_EDIT_INTRO                  1275
#define IDC_SUBJECT_SORT_TYPE           1276
#define IDC_THREAD_BREAK                1277
#define IDC_MERGE_ROOT_FOLDER           1278
#define IDC_LABEL_PER_MBOX_FILE         1279
#define IDC_ASSIGN_LABEL_PER_FOLDER     1280
#define IDC_LABEL_PER_FOLDER            1280
#define IDC_LABEL_NONE                  1281
#define IDC_VALIDATE_MBOX_FILES         1282
#define IDC_RADIO4                      1283
#define IDC_VALIDATE_ALL                1283
#define IDC_SOURCE_ARCHIVE              1284
#define IDC_SELECTED_SUBJECT            1285
#define IDC_HTML_TEXT                   1286
#define IDC_TEXT_TYPE                   1287
#define IDC_HTML_IF                     1288
#define IDC_HTML_TEXT_IF                1288
#define IDC_RESET_MAX_MAIL_SIZE         1289
#define IDC_COLOR_CHECK_ALL             1290
#define IDC_PROGRESS_BAR                1291
#define IDC_COLOR_DFLT                  1292
#define IDC_COLOR_CUSTOM                1293
#define IDC_COLOR_STYLE1                1294
#define IDC_COLOR_STYLE2                1295
#define IDC_COLOR_STYLE3                1296
#define IDC_COLOR_STYLE4                1297
#define IDC_COLOR_STYLE5                1298
#define IDC_COLOR_STYLE6                1299
#define IDC_COLOR_STYLE7                1300
#define IDC_COLOR_STYLE8                1301
#define IDC_COLOR_STYLE_9               1302
#define IDC_COLOR_STYLE_10              1303
#define IDC_COLOR_STYLE_11              1304
#define IDC_COLOR_STYLE_12              1305
#define IDC_COLOR_STYLE_13              1306
#define IDC_COLOR_STYLE_14              1307
#define IDC_COLOR_STYLE_15              1308
#define IDC_COLOR_STYLE_16              1309
#define IDC_APPEND_MULTIPLE_MAILS_VIEW  1310
#define IDC_APPEND_MULTIPLE_MAILS_PRINT 1311
#define IDC_CURRENT_FOLDER_PATH         1312
#define IDC_OPEN_LINK_IN_CURRENT_TAB    1313
#define IDC_FIND_END_DATE               1314
#define IDC_FIND_START_DATE             1315
#define IDC_FIND_DATE_FMT               1316
#define IDC_FIND_ADV_DATE_FMT           1317
#define IDC_HIGHLIGHT_ALL               1318
#define IDC_STATIC_FIND_ADV             1319
#define IDC_STATIC_GB_FIND_ADV_1        1320
#define IDC_STATIC_FIND_ADV_FIIND_WHAT  1321
#define IDC_STATIC_FIND_ADV_MATCH_WORD  1322
#define IDC_STATIC_FIND_ADV_MATCH_CASE  1323
#define IDC_STATIC_GB_FIND_ADV_2        1324
#define IDC_STATIC_GB_FIND_ADV_3        1325
#define IDC_STATIC_FIND_FIND_WHAT       1326
#define IDC_STATIC_GB_FIND_1            1327
#define IDC_STATIC_GB_FIND_2            1328
#define IDC_STATIC_FIND_ADV_START_DATE  1329
#define IDC_STATIC_FIND_ADV_END_DATE    1330
#define IDC_STATIC_OPEN_FILE_OR_FOLDER  1331
#define IDC_STATIC_PRINT_CONFIG_1       1332
#define IDC_STATIC_PRINT_CONFIG_2       1333
#define IDC_STATIC_PRINT_CONFIG_3       1334
#define IDC_STATIC_PRINT_CONFIG_4       1335
#define IDC_STATIC_PRINT_CONFIG_5       1336
#define IDC_STATIC_PRINT_CONFIG_6       1337
#define IDC_STATIC_PRINT_CONFIG_7       1338
#define IDC_STATIC_PRINT_CONFIG_8       1339
#define IDC_STATIC_ABOUT_1              1340
#define IDC_STATIC_ABOUT_2              1341
#define IDC_STATIC_ATTACHMENT_1         1342
#define IDC_STATIC_ATTACHMENT_2         1343
#define IDC_STATIC_ATTACHMENT_3         1344
#define IDC_STATIC_ATTACHMENT_4         1345
#define IDC_STATIC_ATTACHMENT_5         1346
#define IDC_STATIC_ATTACHMENT_6         1347
#define IDC_STATIC_ATTACHMENT_7         1348
#define IDC_STATIC_COLOR_1              1349
#define IDC_STATIC_DATA_FOLDER_CFG_1    1350
#define IDC_STATIC_CREATE_ARCHIVE_1     1351
#define IDC_STATIC_CREATE_ARCHIVE_2     1352
#define IDC_STATIC_CREATE_ARCHIVE_3     1353
#define IDC_STATIC_CREATE_ARCHIVE_4     1354
#define IDC_STATIC_CREATE_ARCHIVE_5     1355
#define IDC_STATIC_EXPORT_CSV_1         1356
#define IDC_STATIC_EXPORT_CSV_2         1357
#define IDC_STATIC_EXPORT_CSV_3         1358
#define IDC_STATIC_EXPORT_CSV_4         1359
#define IDC_STATIC_EXPORT_CSV_5         1360
#define IDC_STATIC_EXPORT_CSV_6         1361
#define IDC_STATIC_EXPORT_CSV_7         1362
#define IDC_STATIC_FIND_1               1363
#define IDC_STATIC_FILTER_RULE_1        1364
#define IDC_STATIC_FILTER_RULE_2        1365
#define IDC_STATIC_FIND_IN_MAIL_1       1366
#define IDC_STATIC_FORWARD_FROM         1367
#define IDC_STATIC_FORWARD_2            1368
#define IDC_STATIC_FORWARD_SUBJECT      1369
#define IDC_STATIC_FONT_FAMILY_1        1370
#define IDC_STATIC_MAIL_HDR_1           1371
#define IDC_STATIC_MAIL_HDR_2           1372
#define IDC_STATIC_MAIL_HDR_3           1373
#define IDC_STATIC_MAIL_HDR_4           1374
#define IDC_STATIC_TEMPL_CFG_1          1375
#define IDC_STATIC_TEMPL_CFG_2          1376
#define IDC_STATIC_TEMPL_CFG_3          1377
#define IDC_STATIC_TEMPL_CFG_4          1378
#define IDC_STATIC_TEMPL_CFG_5          1379
#define IDC_STATIC_TEMPL_CFG_6          1380
#define IDC_STATIC_TEMPL_CFG_7          1381
#define IDC_STATIC_TEMPL_CFG_8          1382
#define IDC_STATIC_OPEN_ARCHIVE_1       1383
#define IDC_STATIC_OPEN_ARCHIVE_2       1384
#define IDC_STATIC_OPEN_ARCHIVE_3       1385
#define IDC_STATIC_OPEN_ARCHIVE_4       1386
#define IDC_STATIC_OPTIONS_DATE_FMT     1387
#define IDC_STATIC_OPTIONS_SHOW_CHARS   1388
#define IDC_STATIC_OPTION_SORT_SUBJ_TYPE 1389
#define IDC_STATIC_OPTIONS_1            1390
#define IDC_STATIC__PRINT_CFG_1         1391
#define IDC_STATIC_SMTP_1               1392
#define IDC_STATIC_SMTP_2               1393
#define IDC_STATIC_SMTP_3               1394
#define IIDC_STATIC_SMTP_4              1395
#define IDC_STATIC_SMTP_5               1396
#define IDC_STATIC_SMTP_6               1397
#define IDC_STATIC_SMTP_7               1398
#define IDC_STATIC_SMTP_8               1399
#define IDC_STATIC_SMTP_9               1400
#define IDC_STATIC_FILTER_RULE_3        1401
#define IDC_STATIC_FILTER_RULE_4        1402
#define IDC_STATIC_FILTER_RULE_5        1403
#define IDC_STATIC_FILTER_RULE_6        1404
#define IDC_STATIC_FILTER_RULE_7        1405
#define IDC_LIST_FONT_FAMILY            1406
#define IDC_LIST_COLOR_STYLE_PANES      1407
#define IDC_LIST_CHECK_LIST_BOX         1408
#define IDC_STATIC_SELECT_LANG_1        1409
#define IDC_LIST_SELECT_LANG            1410
#define IDC_SELECT_OK_TO_SELECT_DFLT_DATA_FOLDER 1411
#define IDC_DATA_FOLDER_INTRO_1         1412
#define IDC_MERGE_FOLDERS_INTRO_1       1413
#define IDC_EDIT_LOCATION_PATH          1414
#define IDC_STATIC_NEW_FOLDER           1415
#define IDC_STATIC_PANE_COLOR_TEXT      1416
#define IDC_STATIC_EXPORT_EML_TEXT      1417
#define IDC_STATIC_OPTIONS_FROM         1418
#define IDC_STATIC_OPTIONS_TO           1419
#define IDC_STATIC_OPTIONS_SUBJECT      1420
#define IDC_STATIC_PDF_MERGE            1422
#define IDC_MERGE_HTML_CNT              1423
#define IDC_STATIC_MERGE_INFO_1         1424
#define IDC_MERGE_USER_AGENT            1425
#define IDC_MERGE_ENABLE_USER_AGENT     1425
#define IDC_FIND_IN_MAIL_STRING         1426
#define IDC_RADIO_FONT_DFLT             1427
#define IDC_STATIC_FONT_CONFIG_1        1428
#define IDC_STATIC_FONT_CONFIG_2        1429
#define IDC_EDIT_CUSTOM_FONT_SIZE       1430
#define IDC_STATIC_FONT_CONFIG_3        1431
#define ID_VIEW_TOOLBARS                32771
#define ID_EDIT_FINDAGAIN               32839
#define ID_FILE_REFRESH                 32840
#define ID_FILE_OPTIONS                 32847
#define ID_EDIT_VIEWEML                 32848
#define ID_Menu                         32849
#define ID_FILE_EXPORT_TO_CSV           32850
#define ID_VIEW_CODEPAGEIDS             32851
#define ID_VIEW_CONVERSATIONS           32852
#define ID_PRINTTO_CSV                  32853
#define ID_PRINTTO_TEXT                 32854
#define ID_PRINTTO_HTML                 32855
#define ByConversation                  32861
#define ID_SORTBY_DATE                  32862
#define ID_SORTBY_FROM                  32863
#define ID_SORTBY_TO                    32864
#define ID_SORTBY_SUBJECT               32865
#define ID_SORTBY_SIZE                  32866
#define ID_SORTBY_CONVERSATION          32867
#define ID_BUTTON32868                  32868
#define ID_TREE_EXPAND                  32868
#define ID_BUTTON32875                  32875
#define ID_TREE_HIDE                    32875
#define ID_BUTTON32876                  32876
#define ID_VIEW_USERSELECTEDMAILS       32878
#define ID_HELP_MBOXVIEWHELP            32879
#define ID_EDIT_FINDADVANCED            32880
#define ID_VIEW_MESSAGEWINDOW           32881
#define ID_MESSAGEWINDOW_BOTTOM         32882
#define ID_MESSAGEWINDOW_RIGHT          32883
#define ID_MESSAGEWINDOW_LEFT           32884
#define ID_FILE_PRINTCONFIG             32885
#define ID_FILE_MERGEARCHIVEFILES       32886
#define ID_PRINTTO_PDF                  32887
#define ID_FILE_ATTACHMENTSCONFIG       32888
#define ID_FILE_COLORCONFIG             32889
#define ID_Menu32891                    32891
#define ID_FORDEVELOPERS_SORTBYID       32892
#define ID_FORDEVELOPERS_MEMORY         32893
#define ID_VIEW_MESSAGEHEADERS          32894
#define ID_FILE_RESTOREHINTMESSAGES     32895
#define ID_VIEW_MESSAGEHEADERPANELAYOUT 32896
#define ID_MESSAGEHEADERPANELAYOUT_DEFAULT 32897
#define ID_MESSAGEHEADERPANELAYOUT_EXPANDED 32898
#define ID_FILE_SMTPMAILSERVERCONFIG    32899
#define ID_HELP_USERGUIDE               32900
#define ID_HELP_README                  32901
#define ID_HELP_LICENSE                 32902
#define ID_FILE_GMAILLABELS             32903
#define ID_GMAILLABELS_CREATE           32904
#define ID_GMAILLABELS_DELETE           32905
#define ID_GMAILLABELS_REFRESH          32906
#define ID_FILE_SELECTROOTFOLDER        32907
#define ID_FILE_DATAFOLDERCONFIG        32908
#define ID_HELP_DONATE                  32909
#define ID_SELECTASROOTFOLDER_LABELTREEV 32910
#define ID_SELECTASROOTFOLDER_FOLDERTREEVIEW 32911
#define ID_FILE_MERGEROOTFOLDERSUB      32912
#define ID_FILE_SELECTASROOTFOLDER      32913
#define ID_DEVELOPMENTOPTIONS_DUMPRAWDATA 32914
#define ID_DEVELOPMENTOPTIONS_DEVELO    32915
#define ID_DEVELOPMENTOPTIONS_ABOUTSYSTEM 32916
#define ID_DEVELOPMENTOPTIONS_RELAXMAILFILEVALIDATION 32917
#define ID_FILE_GENERALOPTIONS          32918
#define ID_FILE_GENERALOPTIONS32919     32919
#define ID_HELP_CHANGE_LOG              32920
#define ID_HELP_SHORTCUTS               32921
#define ID_FILE_SELECT_FOLDER           32922
#define ID_DEVELOPMENTOPTIONS_PRINTRESOURCCES 32923
#define ID_DEVELOPMENTOPTIONS_CODEPAGEINSTALLED 32924
#define ID_DEVELOPMENTOPTIONS_CREATELANGUAGEFILE 32925
#define ID_DEVELOPMENTOPTIONS_SELECTLANGUAGE 32926
#define ID_DEVELOPMENTOPTIONS_LANGUAGETOOLS 32927
#define ID_LANGUAGETOOLS_CREATERESOURCEFILE 32928
#define ID_LANGUAGETOOLS_CREATETRANSLATIONFILE 32929
#define ID_LANGUAGETOOLS_RESORTTRANSLATIONFILE 32930
#define ID_LANGUAGETOOLS_RESOURCEFILEPROPERTY 32931
#define ID_HELP_FILEBASEDCONFIG         32932
#define ID_LANGUAGETOOLS_SPLITTRANSLATIONFILE 32933
#define ID_LANGUAGE                     32934
#define ID_LANGUAGE_SELECTLANGUANGE     32935
#define ID_LANGUAGE_HELP                32936
#define ID_DEVELOPMENTOPTIONS_TEST      32937
#define ID_TEST_CFILEOPENFAILURE        32938
#define ID_FILE_FONTCONFIG              32939
#define ID_INDICATOR_MAIL               59142
#define ID_INDICATOR_MAIL_INDEX         59143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        246
#define _APS_NEXT_COMMAND_VALUE         32940
#define _APS_NEXT_CONTROL_VALUE         1432
#define _APS_NEXT_SYMED_VALUE           118
#endif
#endif
