//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mboxview.rc
//
#define IDD_ABOUTBOX                    100
#define IDS_MAIN_TOOLBAR                101
#define IDD_CPICTURECTRLDEMO_DIALOG     102
#define IDR_MAINFRAME                   128
#define IDR_mboxviewTYPE                129
#define IDS_SELECT_FOLDER               129
#define IDR_POPUP_TOOLBAR               131
#define IDD_CONTROLS_DLG                154
#define IDB_IL_TREE                     155
#define IDD_FIND                        156
#define IDD_OPTIONS                     158
#define IDD_EXPORT_TO_CSV               166
#define IDD_OPEN_FOLDER                 168
#define IDB_PRINT                       171
#define IDB_FOLDER                      176
#define IDD_FIND_ADVANCED               177
#define IDD_FIND_IN_MAIL                180
#define IDD_EDITOR                      194
#define IDD_PRINT_DLG                   195
#define IDD_INPUT_BOX_DLG               201
#define IDS_DESC_TITLE                  202
#define IDS_TITLE_SUBJECT               202
#define IDS_DESC_TITLE1                 203
#define IDS_TITLE_FROM                  203
#define IDD_ATTACHMENTS_CONFIG          203
#define IDS_DESC_NONE                   204
#define IDS_DESC_TITLE3                 205
#define IDS_TITLE_TO                    205
#define IDD_CHECK_LIST_BOX_DLG          205
#define IDS_DESC_TITLE2                 206
#define IDS_TITLE_DATE                  206
#define IDS_DESC_BODY                   207
#define IDS_TITLE_BODY                  207
#define IDB_PAPER_CLIP                  207
#define IDD_NAME_TEMPL_DLG              208
#define IDS_TITLE_CC                    208
#define IDS_TITLE_BCC                   209
#define IDS_TITLE_MAIL_HEADER           210
#define IDD_COLOR_STYLE_DLG             216
#define IDD_HTML_PDF_HDR_DLG            218
#define IDD_GENERIC_FONT_DLG            220
#define IDB_BITMAP1                     222
#define IDD_FIND_FILTER_DLG             223
#define IDD_DIALOG1                     225
#define IDD_OPEN_ARCHIVE_DLG            225
#define IDD_SMTP_DLG                    226
#define IDD_FORWARD_EMAIL               228
#define IDD_DATA_FOLDER_DLG             230
#define IDD_MERGE_FOLDER_AND_SUBFOLDERS 232
#define IDD_DEV_CREATE_ARCHIVE          234
#define IDD_PAGE_CODE_LIST_DLG          236
#define IDC_BUTTON_PREV                 1001
#define IDC_PRT_PAGE_SETP               1001
#define IDC_EDIT_RESET                  1001
#define IDC_SRCFTIME                    1001
#define IDC_BUTTON2                     1002
#define IDC_BUTTON_NEXT                 1002
#define IDC_BUTTON_ROTATE               1003
#define IDC_STATIC_PICTURE              1006
#define IDC_COMPANY_URL                 1041
#define IDC_TREE                        1042
#define IDC_LIST                        1043
#define IDC_BROWSER                     1044
#define IDC_EXPLORER                    1045
#define IDC_ATTACHMENTS                 1046
#define IDC_STRING                      1047
#define IDC_CASE                        1048
#define IDC_WHOLE                       1049
#define IDC_STATIC1                     1050
#define IDC_DMY                         1051
#define IDC_MDY                         1052
#define IDC_YMD                         1053
#define IDC_DATETIMEPICKER1             1053
#define IDC_DATETIMEPICKER2             1054
#define IDC_SCOPE                       1056
#define IDC_EXPORT_EML                  1056
#define IDC_SEARCH_PREV                 1056
#define IDC_ENCODING_NONE               1056
#define IDC_ARCHIVE_LIST                1056
#define IDC_FILTER1                     1056
#define IDC_PRT_DO_NOT_PROMPT           1056
#define IDC_COLOR_DFLT                  1056
#define IDC_FONT_DFLT                   1056
#define IDC_FILTER_NUMBER0              1056
#define IDC_RADIO2                      1057
#define IDC_EXPORT_EML_Y                1057
#define IDC_FIND_LIST                   1057
#define IDC_FILTER_NUMBER1              1057
#define IDC_MERGE_ROOT_FOLDER_AND_SUBFOLDERS 1057
#define IDC_FILTER_NUMBER3              1058
#define IDC_CHECK1                      1059
#define IDC_FILTERDATES                 1059
#define IDC_EXPORT_FROM                 1059
#define IDC_CHECK_FROM_A                1059
#define IDC_FILE_DATE                   1059
#define IDC_ENHANCED_SELECT_FOLDER      1059
#define IDC_ALL_ATTACHMENT_TYPES        1059
#define IDC_COLOR_CHECK                 1059
#define IDC_FLD_NAME_BOLD               1059
#define IDC_FILTER_NUMBER2              1059
#define IDC_SSL_ON                      1059
#define IDC_CHECK_TO_A                  1060
#define IDC_EDIT_TO_CHECKED             1060
#define IDC_ALL_ATTACHMENT_TYPES_INDICATOR 1060
#define IDC_FILTER_NUMBER4              1060
#define IDC_CHECK_SUBJECT_A             1061
#define IDC_EDIT_SUBJECT_CHECKED        1061
#define IDC_CHECK_MESSAGE_A             1062
#define IDC_EDIT_MESSAGE_CHECKED        1062
#define IDC_DONATION                    1063
#define IDC_CHECK_ATTACHMENTS_A         1063
#define IDC_EDIT_ATTACHMENT_CHECKED     1063
#define IDC_FILTERDATES_A               1064
#define IDC_EDIT_ATTACHMENT_NAME_CHECKED 1064
#define IDC_PROGRESS_BAR_DELAY          1065
#define IDC_MSEDGE                      1066
#define IDC_SUBJ_ID                     1070
#define IDC_FROM_ID                     1071
#define IDC_CONFIG_FOLDER_STYLE_1       1071
#define IDC_TO_ID                       1072
#define IDC_CONFIG_FOLDER_STYLE_2       1072
#define IDC_CONFIG_FOLDER_STYLE_3       1073
#define IDC_SHOW_CHARSETS               1074
#define IDC_SHOW_CHARSETS_Y             1075
#define IDC_COLOR_STYLE4                1075
#define IDC_CHECK_FROM                  1076
#define IDC_CHECK_TO                    1077
#define IDC_CHECK_SUBJECT               1078
#define IDC_CHECK_CONTENT               1079
#define IDC_CHECK6                      1080
#define IDC_CHECK_ATTACHMENT            1080
#define IDC_EDIT_CC_CASE                1080
#define IDC_SEPARATE_TEXT               1080
#define IDC_SEARCH_NEXT                 1081
#define IDC_BUTTON_ZOOM                 1083
#define IDC_CHECK3                      1085
#define IDC_IMAGE_VIEWER                1085
#define IDC_EXPORT_SUBJECT              1085
#define IDC_MATCH_CASE                  1085
#define IDC_EDIT_FROM_CASE              1085
#define IDC_FILE_FROM                   1085
#define IDC_CHECK_BCC                   1085
#define IDC_TEMPL_FROM_DOMAIN_NAME      1085
#define IDC_TIME_TYPE                   1086
#define IDC_MATCH_CASE2                 1086
#define IDC_EDIT_TO_CASE                1086
#define IDC_ATTACHMENT_TYPE_INDICATOR   1086
#define IDC_TEMPL_TO_DOMAIN_NAME        1086
#define IDC_TIME_LOCAL                  1087
#define IDC_MATCH_CASE3                 1087
#define IDC_EDIT_SUBJECT_CASE           1087
#define IDC_TIME_GMT                    1088
#define IDC_MATCH_CASE4                 1088
#define IDC_EDIT_MESSAGE_CASE           1088
#define IDC_GROUP_PROGRES_BAR           1089
#define IDC_MATCH_CASE5                 1089
#define IDC_EDIT_ATTACHMENT_CASE        1089
#define IDC_GROUP_EML                   1090
#define IDC_EDIT_ATTACHMENT_NAME_CASE   1090
#define IDC_GROUP_SET_IDS               1091
#define IDC_GROUP_SHOW_CHARSETS         1092
#define IDC_GROUP_FROM_TO_SUBJ          1093
#define IDC_OPTIONS_SEPARATOR           1094
#define IDC_PICTURE_VIEWER              1095
#define IDC_EXPORT_TO                   1096
#define IDC_EXPORT_DATE                 1097
#define IDC_EXPORT_MESSAGE              1098
#define IDC_COLOR_CUSTOM                1101
#define IDC_ENCODING_UTF8               1106
#define IDC_ENCODING_CODE_PAGE          1107
#define IDC_ENCODING_CODE_PAGE_ID       1108
#define IDC_BUTTON_PRT                  1109
#define IDC_EDIT1                       1110
#define IDC_EDIT_FROM                   1110
#define IDC_FILE_NAME_FORMAT            1110
#define IDC_FILE_NAME_ADJUSTED_MAX_SIZE 1110
#define IDC_EXPORT_MESSAGE_LIMIT_CHARS  1110
#define IDC_MATCH_WORD                  1111
#define IDC_EDIT_FROM_WHOLE             1111
#define IDC_REGULAR_EXPR                1112
#define IDC_EDIT2                       1113
#define IDC_EDIT_TO                     1113
#define IDC_FILE_NAME_MAX_SIZE          1113
#define IDC_MATCH_WORD2                 1114
#define IDC_EDIT_TO_WHOLE               1114
#define IDC_REGULAR_EXPR2               1115
#define IDC_EDIT3                       1116
#define IDC_EDIT_SUBJECT                1116
#define IDC_CHROME_EXE_PATH             1116
#define IDC_USER_ACCOUNT                1116
#define IDC_EDIT_FORWARD_BCC            1116
#define IDC_MAIL_LEADING_CNT            1116
#define IDC_MATCH_WORD3                 1117
#define IDC_EDIT_SUBJECT_WHOLE          1117
#define IDC_REGULAR_EXPR3               1118
#define IDC_EDIT4                       1119
#define IDC_EDIT_MESSAGE                1119
#define IDC_HTML2PDF_SCRIPT_PATH        1119
#define IDC_USER_PASSWORD               1119
#define IDC_EDIT_FORWARD_TEXT           1119
#define IDC_MAIL_TRAILING_CNT           1119
#define IDC_MATCH_WORD4                 1120
#define IDC_EDIT_MESSAGE_WHOLE          1120
#define IDC_REGULAR_EXPR4               1121
#define IDC_EDIT5                       1122
#define IDC_EDIT_ATTACHMENT             1122
#define IDC_EDIT_FORWARD_SERVICE        1122
#define IDC_CREATED_ARCHIVE             1122
#define IDC_MATCH_WORD5                 1123
#define IDC_EDIT_ATTACHMENT_WHOLE       1123
#define IDC_REGULAR_EXPR5               1124
#define IDC_EDIT_ATTACHMENT_NAME        1124
#define IDC_SEARCH_BACKWARDS_A          1125
#define IDC_EDIT_ATTACHMENT_NAME_WHOLE  1125
#define IDC_MATCH_WORDS_ALL_A           1142
#define IDC_EDIT_SET_ALL_WHOLE          1142
#define IDC_MATCH_CASE_ALL_A            1143
#define IDC_EDIT_SET_ALL_CASE           1143
#define IDC_REGEX_ALL_A                 1144
#define IDC_CHECK_HIGHLIGHT_ALL         1145
#define IDC_SLIDER_ZOOM                 1146
#define IDC_SLIDER_POS                  1149
#define IDC_EXPORT_MESSAGE_LIMIT        1150
#define IDC_FIND_ALL_OCCURENCES         1151
#define IDC_CHECK_FIND_ALL              1151
#define IDC_EDIT_LIST                   1152
#define IDC_EDIT_FROM_CHECKED           1157
#define IDC_FILE_TIME                   1158
#define IDC_FILE_TO                     1159
#define IDC_FILE_SUBJECT                1160
#define IDC_FILE_UNIQUE_ID              1161
#define IDC_PRT_PREVIEW_DIALOG          1162
#define IDC_PRT_PRINT_DIALOG            1163
#define IDC_HTML2PDF_SCRIPT_TYPE        1164
#define IDC_USER_SCRIPT                 1165
#define IDC_EDIT_CC_CHECKED             1169
#define IDC_EDIT_CC                     1170
#define IDC_EDIT_CC_WHOLE               1171
#define IDC_EDIT_BCC_CHECKED            1172
#define IDC_EDIT_BCC                    1173
#define IDC_EDIT_BCC_WHOLE              1174
#define IDC_EDIT_BCC_CASE               1175
#define IDC_PRINT_TO_SEPARATE_FILES     1176
#define IDC_SEPARATE_PDF                1177
#define IDC_SEPARATE_HTML               1178
#define IDC_STATIC_PDF_OPTIONS          1179
#define IDC_ADD_HDR_COLOR               1180
#define IDC_PAGE_BREAK                  1181
#define IDC_EXPORT_CC                   1182
#define IDC_EXPORT_BCC                  1183
#define IDC_CHECK2                      1184
#define IDC_CHECK_CC                    1184
#define IDC_EXPORT_ATTACHMENT_NAMES     1184
#define IDC_CHECK_NEGATE_FIND_CRITERIA  1184
#define IDC_KEEP_BODY_BKGRND_COLOR      1184
#define IDC_TEMPL_FROM_USERNAME         1184
#define IDC_TEMPL_TO_USERNAME           1185
#define IDC_INPUT_LABEL                 1186
#define IDC_LIST2                       1187
#define IDC_CODE_PAGE_ENUMERATION       1187
#define IDC_CHECK_ATTACHMENT_NAME       1188
#define IDC_CHECK_NEGATE_SEARCH_CRITERIA 1189
#define IDC_LICENSE                     1190
#define IDC_FOLDER_LIST                 1191
#define IDC_ATTACHMENT_WNDW_CFG         1192
#define IDC_ATTACHMENT_MAX_SIZE         1193
#define IDC_LIST1                       1194
#define IDC_CUSTOM_TEMPLATE             1195
#define IDC_SET_CUSTOM_TEMPLATE         1196
#define IDC_LABEL_LIST                  1197
#define IDC_EDIT_TEMPL_FMT              1199
#define IDC_EDIT_DATE_FMT               1200
#define IDC_TEMPL_FROM_ADDRESS_TEXT     1206
#define IDC_TEMPL_WHITE_TO_UNDERSCORE   1207
#define IDC_TEMPL_TO_ADDRESS_TEXT       1208
#define IDC_COLOR_BUTTON                1212
#define IDC_COLOR_STYLE1                1214
#define IDC_COLOR_STYLE2                1215
#define IDC_COLOR_STYLE3                1216
#define IDC_COLOR_STYLE5                1217
#define IDC_COLOR_STYLE6                1218
#define IDC_COLOR_STYLE7                1219
#define IDC_COLOR_STYLE8                1220
#define IDC_BUTTON_HELP                 1221
#define IDC_BUTTON_CLOSE                1222
#define IDC_PICK_FAMILY_FONT            1223
#define IDC_FONT_CUSTOM                 1224
#define IDC_FLD_SIZE                    1225
#define IDC_PICK_CONCRETE_FONT          1226
#define IDC_HDR_FLD_HELP                1227
#define IDC_HDR_FLD_NAME                1228
#define IDC_HDR_FLD_TEXT                1229
#define IDC_BUTTON1                     1230
#define IDC_HTML_PDF_CNF                1230
#define IDC_EXPORT_ATTACHMENT_SEPARATOR 1231
#define IDC_EDIT_MAIL_HDR               1232
#define IDC_RULE_NUMBER_TEXT            1237
#define IDC_RULE_TEXT                   1238
#define IDC_SINGLE_TO                   1239
#define IDC_FILTER_NUMBER5              1240
#define IDC_EDIT_TARGET_FOLDER          1241
#define IDC_EDIT_ARCHIVE_FILE_NAME      1242
#define IDC_EDIT_DFLT_FOLDER            1243
#define IDC_CHECK4                      1244
#define IDC_HEADER_AND_FOOTER           1244
#define IDC_PLAIN_TEXT                  1244
#define IDC_GMAIL                       1245
#define IDC_YAHOO                       1246
#define IDC_OUTLOOK                     1247
#define IDC_CUSTOM                      1248
#define IDC_SMTP_SERVER_ADDR            1249
#define IDC_SMTP_SERVER_PORT            1250
#define IDC_TLS_OPTION                  1251
#define IDC_SSL_OPTION                  1252
#define IDC_RADIO3                      1253
#define IDC_BBUTTON_SAVE                1254
#define IDC_SMTP_SERVER_HELP            1256
#define IDC_FORWARD_TO                  1257
#define IDC_EDIT_FORWARD_TO             1258
#define IDC_EDIT_FORWARD_CC             1259
#define IDC_FORWARD_USER_TEXT           1261
#define IDC_EDIT_FORWARD_SUBJECT        1262
#define IDC_FORWARD_CLEAR               1263
#define IDC_EDIT_FORWARD_FROM           1264
#define IDC_FORWARD_MAX_MAIL_SIZE       1265
#define IDC_FORWARD_MAX_MAIL_SIZE_LABEL 1265
#define IDC_MAX_MAIL_SIZE               1266
#define IDC_SELECT_DATA_FOLDER_BUTTON   1268
#define IDC_EDIT_WIN_APP_DATA_FOLDER    1269
#define IDC_USER_SELECTED_FOLDER_PATH   1270
#define IDC_EDIT_INTRO                  1275
#define IDC_SUBJECT_SORT_TYPE           1276
#define IDC_THREAD_BREAK                1277
#define IDC_MERGE_ROOT_FOLDER           1278
#define IDC_LABEL_PER_MBOX_FILE         1279
#define IDC_ASSIGN_LABEL_PER_FOLDER     1280
#define IDC_LABEL_PER_FOLDER            1280
#define IDC_LABEL_NONE                  1281
#define IDC_VALIDATE_MBOX_FILES         1282
#define IDC_RADIO4                      1283
#define IDC_VALIDATE_ALL                1283
#define IDC_SOURCE_ARCHIVE              1284
#define IDC_SELECTED_SUBJECT            1285
#define IDC_HTML_TEXT                   1286
#define IDC_TEXT_TYPE                   1287
#define IDC_HTML_IF                     1288
#define IDC_HTML_TEXT_IF                1288
#define IDC_RESET_MAX_MAIL_SIZE         1289
#define ID_VIEW_TOOLBARS                32771
#define ID_EDIT_FINDAGAIN               32839
#define ID_FILE_REFRESH                 32840
#define ID_FILE_OPTIONS                 32847
#define ID_EDIT_VIEWEML                 32848
#define ID_Menu                         32849
#define ID_FILE_EXPORT_TO_CSV           32850
#define ID_VIEW_CODEPAGEIDS             32851
#define ID_VIEW_CONVERSATIONS           32852
#define ID_PRINTTO_CSV                  32853
#define ID_PRINTTO_TEXT                 32854
#define ID_PRINTTO_HTML                 32855
#define ByConversation                  32861
#define ID_SORTBY_DATE                  32862
#define ID_SORTBY_FROM                  32863
#define ID_SORTBY_TO                    32864
#define ID_SORTBY_SUBJECT               32865
#define ID_SORTBY_SIZE                  32866
#define ID_SORTBY_CONVERSATION          32867
#define ID_BUTTON32868                  32868
#define ID_TREE_EXPAND                  32868
#define ID_BUTTON32875                  32875
#define ID_TREE_HIDE                    32875
#define ID_BUTTON32876                  32876
#define ID_VIEW_USERSELECTEDMAILS       32878
#define ID_HELP_MBOXVIEWHELP            32879
#define ID_EDIT_FINDADVANCED            32880
#define ID_VIEW_MESSAGEWINDOW           32881
#define ID_MESSAGEWINDOW_BOTTOM         32882
#define ID_MESSAGEWINDOW_RIGHT          32883
#define ID_MESSAGEWINDOW_LEFT           32884
#define ID_FILE_PRINTCONFIG             32885
#define ID_FILE_MERGEARCHIVEFILES       32886
#define ID_PRINTTO_PDF                  32887
#define ID_FILE_ATTACHMENTSCONFIG       32888
#define ID_FILE_COLORCONFIG             32889
#define ID_Menu32891                    32891
#define ID_FORDEVELOPERS_SORTBYID       32892
#define ID_FORDEVELOPERS_MEMORY         32893
#define ID_VIEW_MESSAGEHEADERS          32894
#define ID_FILE_RESTOREHINTMESSAGES     32895
#define ID_VIEW_MESSAGEHEADERPANELAYOUT 32896
#define ID_MESSAGEHEADERPANELAYOUT_DEFAULT 32897
#define ID_MESSAGEHEADERPANELAYOUT_EXPANDED 32898
#define ID_FILE_SMTPMAILSERVERCONFIG    32899
#define ID_HELP_USERGUIDE               32900
#define ID_HELP_README                  32901
#define ID_HELP_LICENSE                 32902
#define ID_FILE_GMAILLABELS             32903
#define ID_GMAILLABELS_CREATE           32904
#define ID_GMAILLABELS_DELETE           32905
#define ID_GMAILLABELS_REFRESH          32906
#define ID_FILE_SELECTROOTFOLDER        32907
#define ID_FILE_DATAFOLDERCONFIG        32908
#define ID_HELP_DONATE                  32909
#define ID_SELECTASROOTFOLDER_LABELTREEV 32910
#define ID_SELECTASROOTFOLDER_FOLDERTREEVIEW 32911
#define ID_FILE_MERGEROOTFOLDERSUB      32912
#define ID_FILE_SELECTASROOTFOLDER      32913
#define ID_DEVELOPMENTOPTIONS_DUMPRAWDATA 32914
#define ID_DEVELOPMENTOPTIONS_DEVELO    32915
#define ID_DEVELOPMENTOPTIONS_ABOUTSYSTEM 32916
#define ID_INDICATOR_MAIL               59142
#define ID_INDICATOR_MAIL_INDEX         59143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        238
#define _APS_NEXT_COMMAND_VALUE         32917
#define _APS_NEXT_CONTROL_VALUE         1290
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
